First part
glebhg/css pull request #3
Opened 2021-06-30 14:51 UTC by NatalliaMil

Only part of the task

2021-06-30 21:24 UTC, glebhg requested changes
1. Please rename file `optimizing css.png` to `optimizing_css.png`. Using whitespaces in file names if a bad practise.
2. Rename `..png` file to something readable, like `dot.png`
3. Please, don't use `position: absolute` extensively, only when it is really needed

2021-06-30 21:24 UTC, glebhg commented on nata/simpleBlogHomePage/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;900&display=swap" rel="stylesheet">
```suggestion
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@900&family=Source+Sans+Pro:wght@400;900&display=swap" rel="stylesheet">
```

2021-06-30 21:24 UTC, glebhg commented on nata/simpleBlogHomePage/index.html
> +                    <img src="./Img/github.png" alt="Github" width="20px" height="20px" /></a>
1. All images are blurry, just remove width and height attributes

```suggestion
                <a href="https://www.twitter.com/">
                    <img src="./Img/twitter.png" alt="Twitter" /></a>

                <a href="https://www.dribbble.com/">
                    <img src="./Img/dribbble.png" alt="Dribbble" /></a>

                <a href="https://www.figma.com/">
                    <img src="./Img/figma.png" alt="Figma" /></a>

                <a href="https://www.github.com/">
                    <img src="./Img/github.png" alt="Github" /></a>
```

2. Please rename `Img` folder just as `img`

2021-06-30 21:24 UTC, glebhg commented on nata/simpleBlogHomePage/styles.css
> +    position: absolute;
Bad idea to make the block absolutely positioned and you don't need it here
```suggestion
    position: relative;
```

2021-06-30 21:24 UTC, glebhg commented on nata/simpleBlogHomePage/styles.css
> +    right: 148px;
```suggestion
```

2021-06-30 21:24 UTC, glebhg commented on nata/simpleBlogHomePage/styles.css
> +
How about:

```suggestion
body {
  margin: 8px 10% 0 10%;
}
```

This will position the whole content in the center of a page

2021-06-30 21:24 UTC, glebhg commented on nata/simpleBlogHomePage/styles.css
> +}
Try to rewrite this code without position absolute

2021-06-30 21:24 UTC, glebhg commented on nata/simpleBlogHomePage/styles.css
> +#front-end {
I would avoid using id. Also names should be consistent: if you use hyphens (front-end) use them everywhere.

2021-07-14 10:51 UTC, glebhg approved these changes

2021-07-14 10:51 UTC, glebhg commented on nata/simpleBlogHomePage/index.html
> +        <a href="./"><img src="./img/dasdas.png" alt="Dasdas Logo" /></a>
```suggestion
        <a href="/">
          <img src="./img/dasdas.png" alt="Dasdas Logo" />
        </a>
```

2021-07-14 10:51 UTC, glebhg commented on nata/simpleBlogHomePage/index.html
> +                    <img src="./img/github.png" alt="Github" /></a>
I see here a very good candidate for the list of menu links: `<ul>`. Every `<li>` may contain a link with the image icon. Don't forget about semantically good HTML.

2021-07-14 10:51 UTC, glebhg commented
You can merge this PR

2021-07-14 10:55 UTC, glebhg commented on nata/simpleBlogHomePage/index.html
> +      href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@900&display=swap"
You forgot to add Roboto font

2021-07-14 16:13 UTC, NatalliaMil commented on nata/simpleBlogHomePage/index.html
> +                    <img src="./img/github.png" alt="Github" /></a>
Это устаревшая часть кода. В последнем варианте эта часть уже список.

2021-07-14 16:16 UTC, merged